name: Format

on:
  workflow_call:

jobs:
  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Check code formatting
        run: uv run ruff format --check .